"""Add level_of_education field to users table

Revision ID: b68a022b1d28
Revises: 
Create Date: 2025-05-26 16:17:46.108341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68a022b1d28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level_of_education', sa.String(length=100), nullable=True))
    op.create_index('idx_users_level_of_education', 'users', ['level_of_education'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_level_of_education', table_name='users')
    op.drop_column('users', 'level_of_education')
    # ### end Alembic commands ###
